<?php
require_once($_SERVER['DOCUMENT_ROOT']."/ael/includes/config.php");
require_once(LIB_PATH."log.php");
require_once(LIB_PATH."logReadable.php");
require_once(LIB_PATH."database.php");
require_once(LIB_PATH."databaseObject.php");
require_once(LIB_PATH."complaint.php");
require_once(LIB_PATH."department.php");
require_once(LIB_PATH."problem.php");
require_once(LIB_PATH."plant.php");
require_once(LIB_PATH."user.php");
require_once(LIB_PATH."employee.php");
require_once(LIB_PATH."session.php");
require_once(LIB_PATH."functions.php");
